(load "data-struct/set/test-set.lisp")
(load "data-struct/pot-set/test-pot-set.lisp")
(load "data-struct/tree/test-tree.lisp")
(load "data-struct/prop-logic/test-prop-logic.lisp")
(load "test/test-mdp.lisp")
(load "test/test-rl.lisp")
(load "test/test-alisp.lisp")
#+concurrent-alisp (load "test/test-calisp.lisp")